package bb.aa.androidprotobufdemo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

public final class My {
  private My() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 age = 1;</code>
     */
    boolean hasAge();
    /**
     * <code>required int32 age = 1;</code>
     */
    int getAge();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageLite<
          Person, Person.Builder> implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    private Person() {
      name_ = "";
    }
    private int bitField0_;
    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <code>required int32 age = 1;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 age = 1;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>required int32 age = 1;</code>
     */
    private void setAge(int value) {
      bitField0_ |= 0x00000001;
      age_ = value;
    }
    /**
     * <code>required int32 age = 1;</code>
     */
    private void clearAge() {
      bitField0_ = (bitField0_ & ~0x00000001);
      age_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private String name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>required string name = 2;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
    }
    /**
     * <code>required string name = 2;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>required string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, age_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getName());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static My.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static My.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static My.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static My.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static My.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static My.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static My.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static My.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static My.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static My.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(My.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Person, Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        My.PersonOrBuilder {
      // Construct using My.Person.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 age = 1;</code>
       */
      public boolean hasAge() {
        return instance.hasAge();
      }
      /**
       * <code>required int32 age = 1;</code>
       */
      public int getAge() {
        return instance.getAge();
      }
      /**
       * <code>required int32 age = 1;</code>
       */
      public Builder setAge(int value) {
        copyOnWrite();
        instance.setAge(value);
        return this;
      }
      /**
       * <code>required int32 age = 1;</code>
       */
      public Builder clearAge() {
        copyOnWrite();
        instance.clearAge();
        return this;
      }

      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>required string name = 2;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new My.Person();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasAge()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasName()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          My.Person other = (My.Person) arg1;
          age_ = visitor.visitInt(
              hasAge(), age_,
              other.hasAge(), other.age_);
          name_ = visitor.visitString(
              hasName(), name_,
              other.hasName(), other.name_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  age_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  name_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (My.Person.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Person)
    private static final My.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static My.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Person> PARSER;

    public static com.google.protobuf.Parser<Person> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FamilyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Family)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .Person person = 1;</code>
     */
    java.util.List<Person>
        getPersonList();
    /**
     * <code>repeated .Person person = 1;</code>
     */
    My.Person getPerson(int index);
    /**
     * <code>repeated .Person person = 1;</code>
     */
    int getPersonCount();
  }
  /**
   * Protobuf type {@code Family}
   */
  public  static final class Family extends
      com.google.protobuf.GeneratedMessageLite<
          Family, Family.Builder> implements
      // @@protoc_insertion_point(message_implements:Family)
      FamilyOrBuilder {
    private Family() {
      person_ = emptyProtobufList();
    }
    public static final int PERSON_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Person> person_;
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public java.util.List<Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public java.util.List<? extends PersonOrBuilder>
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public My.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public My.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }
    private void ensurePersonIsMutable() {
      if (!person_.isModifiable()) {
        person_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(person_);
       }
    }

    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void setPerson(
        int index, My.Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePersonIsMutable();
      person_.set(index, value);
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void setPerson(
        int index, My.Person.Builder builderForValue) {
      ensurePersonIsMutable();
      person_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void addPerson(My.Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePersonIsMutable();
      person_.add(value);
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void addPerson(
        int index, My.Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePersonIsMutable();
      person_.add(index, value);
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void addPerson(
        My.Person.Builder builderForValue) {
      ensurePersonIsMutable();
      person_.add(builderForValue.build());
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void addPerson(
        int index, My.Person.Builder builderForValue) {
      ensurePersonIsMutable();
      person_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void addAllPerson(
        Iterable<? extends Person> values) {
      ensurePersonIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, person_);
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void clearPerson() {
      person_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    private void removePerson(int index) {
      ensurePersonIsMutable();
      person_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static My.Family parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static My.Family parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static My.Family parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static My.Family parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static My.Family parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static My.Family parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static My.Family parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static My.Family parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static My.Family parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static My.Family parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(My.Family prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Family}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Family, Builder> implements
        // @@protoc_insertion_point(builder_implements:Family)
        My.FamilyOrBuilder {
      // Construct using My.Family.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .Person person = 1;</code>
       */
      public java.util.List<Person> getPersonList() {
        return java.util.Collections.unmodifiableList(
            instance.getPersonList());
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public int getPersonCount() {
        return instance.getPersonCount();
      }/**
       * <code>repeated .Person person = 1;</code>
       */
      public My.Person getPerson(int index) {
        return instance.getPerson(index);
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder setPerson(
          int index, My.Person value) {
        copyOnWrite();
        instance.setPerson(index, value);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder setPerson(
          int index, My.Person.Builder builderForValue) {
        copyOnWrite();
        instance.setPerson(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(My.Person value) {
        copyOnWrite();
        instance.addPerson(value);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(
          int index, My.Person value) {
        copyOnWrite();
        instance.addPerson(index, value);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(
          My.Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPerson(builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(
          int index, My.Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPerson(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addAllPerson(
          Iterable<? extends Person> values) {
        copyOnWrite();
        instance.addAllPerson(values);
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder clearPerson() {
        copyOnWrite();
        instance.clearPerson();
        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        copyOnWrite();
        instance.removePerson(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Family)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new My.Family();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          for (int i = 0; i < getPersonCount(); i++) {
            if (!getPerson(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          person_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          My.Family other = (My.Family) arg1;
          person_= visitor.visitList(person_, other.person_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!person_.isModifiable()) {
                    person_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(person_);
                  }
                  person_.add(
                      input.readMessage(My.Person.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (My.Family.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Family)
    private static final My.Family DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Family();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static My.Family getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Family> PARSER;

    public static com.google.protobuf.Parser<Family> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
